version: '3.1'

services:

  wordpress:
    build: .
    ports:
      - 8888:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/SteveGutenberg
    depends_on:
      - mysql

  cli:
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mysql
      - wordpress
    command: >
      bash -c "
        sleep 10 &&
        wp core install --url=http://localhost:8888/ --title=SteveLand --admin_user=admin --admin_password=very_weak_password --admin_email=cameron.lowe@refinery29.com &&
        wp plugin activate gutenberg &&
        wp plugin activate SteveGutenberg"



  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test

volumes:
  wordpress:
